# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

google-ID: ''

menu:
- {name: 'Категории', path: 'blog', url: 'categories.html'}
- {name: 'Теги', path: 'blog', url: 'tags.html'}
- {name: 'Архив', path: 'menu', url: 'writing.html'}
- {name: 'Обо мне', path: 'menu', url: 'about.html'}
# - {name: 'Контакты', path: 'menu', url: 'contact.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link: 'https://www.facebook.com/aziz.madazimov'}
- {icon: 'twitter', link: 'https://twitter.com/madazimov'}
- {icon: 'instagram', link: 'https://www.instagram.com/madazimov'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/madazimov/'}
- {icon: 'github', link: 'https://www.github.com/madazimov'}
- {icon: 'envelope', link: 'mailto:aziz.madazimov@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'В будущее'
  previous_page: 'В прошлое'

sharing_button_prompt: 'Поделитесь, если Вам понравилось!'

related_posts: 'Вам так же может понравиться:'

post_date_prefix: 'Опубликованно'
